# Generated by Django 3.2.4 on 2021-07-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('ssh_port', models.IntegerField(default=22)),
                ('vendor', models.CharField(choices=[('huawei', '华为'), ('cisco', '思科')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('time', models.DateTimeField(null=True)),
                ('messages', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SwitchesModel',
        ),
    ]
